version: '3.7'
services:
    backend:
        container_name: backend-node
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: always
        ports:
            - '${PORT_BACKEND}:3000'
        depends_on:
            - mongo
        volumes:
            - ./server:/usr/src/app
        command: [ "npm", "start" ]
    frontend:
        container_name: frontend-angular
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '${PORT_FRONTEND}:4200'
        depends_on:
            - backend
        volumes:
            - ./client:/usr/src/app
        logging:
            driver: 'json-file'
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '${PORT_MONGO}:27017'
        command: mongod --quiet --logpath /dev/null
